[package]
org= "ballerina"
name= "openapi"
version= "2.0.1-20240618-0959"

[[platform.java17.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.0.1-20240618-0959.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.0.1-20240618-0959"
