[package]
org= "ballerina"
name= "openapi"
version= "2.0.1"

[[platform.java17.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.0.1-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.0.1-SNAPSHOT"
