[package]
org= "ballerina"
name= "openapi"
version= "2.1.0"

[[platform.java17.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.1.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.1.0-SNAPSHOT"
